# Generated by Django 5.0.6 on 2024-06-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
