# Generated by Django 5.0.6 on 2024-06-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_category_options_menu_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
