# Generated by Django 5.0.6 on 2024-06-19 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_menu_category_alter_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Served', 'Served'), ('In Progress', 'In Progress'), ('Waiting', 'Waiting')], default='available', max_length=200)),
                ('table_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.table')),
            ],
        ),
    ]
