# Generated by Django 5.0.6 on 2024-06-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
